CREATE TABLE IF NOT EXISTS `la_order_receipt_request` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` int unsigned NOT NULL,
  `staff_id` int unsigned NOT NULL,
  `submit_user_id` int unsigned NOT NULL,
  `submit_key` char(64) NOT NULL,
  `request_hash` char(64) NOT NULL,
  `pay_type` tinyint unsigned NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `pay_voucher` varchar(512) NOT NULL,
  `collection_owner` tinyint unsigned NOT NULL DEFAULT 2,
  `status` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '0待审核，1通过，2驳回',
  `pending_order_id` int unsigned GENERATED ALWAYS AS (CASE WHEN `status` = 0 THEN `order_id` ELSE NULL END) STORED,
  `payment_id` int unsigned NOT NULL DEFAULT 0,
  `audit_admin_id` int unsigned NOT NULL DEFAULT 0,
  `audit_time` int unsigned NOT NULL DEFAULT 0,
  `reason` varchar(500) NOT NULL DEFAULT '',
  `create_time` int unsigned NOT NULL,
  `update_time` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_submit_key` (`submit_key`),
  UNIQUE KEY `uk_pending_order` (`pending_order_id`),
  KEY `idx_order_history` (`order_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
